### ISSUE TITLE
Proposal: Provide `@connect` Decorator

### ISSUE THREAD

**Issue by christopherjbaker** [bitovi/ylem#103]
This is a proposal to alter RVM to work via an `@connect` decorator, much like [react-redux](https://redux.js.org/docs/basics/UsageWithReact.html). It would be provided like so:

```javascript
import { connect } from "react-view-model";
import connect from "react-view-model/connect";
```

## Why

The impetus for the change was to make the react components pure, that is: not needing to extend custom classes, and not needing special knowledge inside the component itself. Its use would require only the `@connect()` decorator, and the accompanying viewmodel or state object.

## Usage

This version of RVM would primarily support [can-observe](https://canjs.com/doc/can-observe.html). It might also work with [can-define](https://canjs.com/doc/can-define.html), though there are caveats.

### With a ViewModel constructor

It could work with a ViewModel constructor, giving all the power therein.

```jsx
import observe from "can-observe";
import { connect } from "react-view-model";
import React, { Component } from "react";

class ViewModel extends observe.Object {
  constructor(props) {
    super(props);

    this.first = props.first;
    this.last = props.last;
  }

  get name() {
    return `${this.first} ${this.last}`;
  }
}

@connect(ViewModel)
export default class App extends Component {
  render() {
    return (
      <div>{this.props.name}</div>
    );
  }
}
```

### With an observable object

It could also work with an observable object, perhaps as provided from an external store. This method would not allow for derivative props, but would allow for a shared store between components.

```jsx
import observe from "can-observe";
import { connect } from "react-view-model";
import React, { Component } from "react";

const state = observe({
  name: "Christopher Baker",
});

@connect(state)
export default class App extends Component {
  render() {
    return (
      <div>{this.props.name}</div>
    );
  }
}
```

The following two statements are equivalent.

```
@connect(state)

@connect((props) => {
  return { ...props, state };
})
```

### With a partial observable object

It could also work with part of an observable object. This would suffer the same limitations as above, but would allow the combination of multiple stores.

```jsx
import observe from "can-observe";
import { connect } from "react-view-model";
import React, { Component } from "react";

const appState = observe({
  site: "React View Model",
});

const localState = observe({
  name: "Christopher Baker",
});

@connect((props) => {
  const { site } = appState;
  const { name } = localState;

  return { ...props, site, name };
})
export default class App extends Component {
  render() {
    return (
      <div>{this.props.site} {this.props.name}</div>
    );
  }
}
```

## Notes

This would remove the need for `autobind-method.js`, `make-enumerable.js`, #99, #94, #92, and #85.

**Comment by BigAB** [comment]
I think this is all great, and should be noted that the decorator syntax is unnecessary (but totally awesome if you want to use it), because you could always do...
```js
import MyAwesomeComponent from './awesome-comp';
import { connect } from 'react-view-models';
import observe from "can-observe";

export class ViewModel extends observe.Object {
  constructor(props) {
    super(props);
    Object.assign(this, props);
  }

  get name() {
    return `${this.first} ${this.last}`;
  }
}

export default connect(ViewModel)(MyAwesomeComponent)
```
...which is probably how I would want to use it.

## Methods
So why does this alleviate the need for `autobind-method.js`?

I do think we need to think about what the _context_ of the methods called on the `ViewModel` instance would be, **but I guess if we consider that "the users responsibility" or whatever that's not so bad**.

So those that choose to use **class properties** could do:
```js
class ViewModel extends observe.Object {
  selectCarMake: ( make ) => {
    this.selectedMake = make;
  }
}
```
...and those that like decorators could
```js
class ViewModel extends observe.Object {
  @bind
  selectCarMake( make ) {
    this.selectedMake = make;
  }
}
```
...and those who don't like all that fancy stuff could go with
```js
class ViewModel extends observe.Object {
  constructor(props) {
    super(props);
    this.selectCarMake = this.selectCarMake.bind(this);
  }
  selectCarMake( make ) {
    this.selectedMake = make;
  }
}
```
...I wouldn't but I know there are those who prefer that sort of thing.

Anyway... I think this is the way to go, it matches my initial vision for RVM and seems doable now with our new proxy based observables.

**Comment by mjstahl** [comment]
I agree with the `connect(ViewModel)(ReactComponent)`. It reads very nicely "connect ViewModel with ReactComponent".

I would to propose we take it one step further in that `connect` also sets up the binding for the ViewModel's methods. To use @BigAB's words, "I can't think of a reason to have a method in the ViewModel that I am not going to want bound to this" (I think I paraphrased -- no matter).

But. The moment we don't give the option to have control over your own bindings that is the moment you are going to change the context of a function.

So I would to also propose the another function `connectNotBind` be available to export. This would basically do what the `connect` in the above comments does without any method binding.
