### ISSUE TITLE
Intermittent updates on unmounted component

### ISSUE THREAD

**Issue by DesignByOnyx** [bitovi/ylem#110]
![image](https://user-images.githubusercontent.com/514040/35825637-af91417a-0a73-11e8-9049-b0a21026c882.png)

This happens intermittently, caused when navigating between two pages. Of special note is that some of our components rely on route data (for building URLs for links on the page). So if a user moves from Route A to Route B, the component in Route A is trying to rerender because the route changed. This is supposedly fixed in the "connect" branch.

**Comment by christopherjbaker** [comment]
[the fix](https://github.com/canjs/react-view-model/blob/c577ebc1fb5ed9c868783c836a85448e10cfb8f9/connect.js#L35-L37)
