### ISSUE TITLE
RVM Component appears to not update when only children have changes

### ISSUE THREAD

**Issue by BigAB** [bitovi/ylem#111]
Found in **v1.0.0**

Here is the simplest case:

```js
import React from "react";
import { render } from "react-dom";
import { Component } from "react-view-model";
import DefineMap from "can-define/map/map";

const ViewModel = DefineMap.extend({
  init() {
    setInterval(() => {
      this.time = new Date().toString();
    }, 1000);
  },
  time: {
    default: new Date().toString()
  }
});

class ProblemComponent extends Component {
  render() {
    const { time } = this.viewModel;
    return (
      <div>
        <Wrapper>
          <header>Wrapped: {time}</header>
        </Wrapper>
        <header>NOT Wrapped: {time}</header>
      </div>
    );
  }
}
ProblemComponent.ViewModel = ViewModel;

class Wrapper extends Component {
  render() {
    return <div>{this.props.children}</div>;
  }
}

render(<ProblemComponent />, document.getElementById("app"));

```

You have `ProblemComponent`, whose `viewModel` will periodically update it's `time` property, which in turns re-renders the `ProblemComponent`. If the `Wrapper` component is a `RVM.Component`, and uses `this.props.children` in it's `render()`, wrapped elements will not update, result seen below:

![image](https://user-images.githubusercontent.com/76821/35829947-280340c0-0a8a-11e8-85f6-99a1edb6ca11.png)

The interesting thing is if the `Wrapper` component from the example is just a React component, and not an RVM component, everything works fine.

SO, it's like RVM, is not re-rendering, when the only thing that has changed is the `props.children`

**Comment by BigAB** [comment]
Maybe related maybe not but, in the 2.0.0 branch with `connect()` a similar problem may be occurring when you have accessors on the `children` property, something like this:

```js
class RVMWrapper extends Component {
  render() {
    return <div>{this.props.children}</div>;
  }
}
class VM extends BaseViewModel {
  get children() {
    console.log(this._children);
    return this._children;
  }
  set children(children) {
    this._children = children;
  }
}
var Wrapper = connect(VM)(RVMWrapper);
```

**Comment by BigAB** [comment]
Maybe this is not a big because, I just realized, if I change the example `Wrapper` component to:

```js
class Wrapper extends Component {
  render() {
    return <div>{this.viewModel.children}</div>;
  }
}
```
...it works... which makes sense, because the `property read` from `this.props` is not observable, so it would have to be on `this.viewModel`, which, tough it feels funny, actually makes sense.

**Comment by DesignByOnyx** [comment]
I can confirm - if using a RVM component to render children, you should use `this.viewModel.children` and all is well. This makes sense and I'd vote to close this in favor of documentation.
