### ISSUE TITLE
`npm run develop` and `npm run test` not working

### ISSUE THREAD

**Issue by bgando** [bitovi/ylem#116]
This could be a local environment issue, but after `npm install`ing I was not able to successfully run `npm run develop` (noted in the package.json) or `npm test`. I was able to get all tests running/passing in the browser by using `http-server`.

**Comment by chasenlehara** [comment]
Those are probably left over from using the DoneJS plugin generator and can be removed (along with any DoneJS dependencies).

**Comment by christopherjbaker** [comment]
The only done-x dependency should be done-serve. I do use `npm run develop` for opening the tests in the browser, but it has the `--static` flag, so it should be functionally equavalent to `http-server` or `serve`.

**Comment by christopherjbaker** [comment]
the project was rewritten and both are running properly now
