### ISSUE TITLE
RVM should call `.stopListening` on it's viewModel instance when component unmounts

### ISSUE THREAD

**Issue by BigAB** [bitovi/ylem#117]
May only be applicable to `connect()` and `componentFromViewModel()` as observed state could do it themselves.
Here's a pretty standard problem:

Parent Component passes a callback to a "Smart' component with a viewmodel. The smart component is connected to real-time, or another component or something, so "something" can change the state without interaction on the component from the user.

The most obvious way to make sure the `callback` was called everytime the state changes, even if it wasn't by user interaction, or anything in this component is to just bind to the property itself in the `init` or `constructor`:

```js
class ViewModel extends ObservableObject {
  constructor(...args) {
    super(...args);
    this.on("value", (e, newVal) => {
      this.onChange(newVal);
    });
  }

  get value() {
    return someObservable.property;
  }
}
```
...but this will most likely cause a memory leak, because this event handler is never torn down.

The solution, or one at least, is to use `listenTo` instead of `on`, and then call `viewModel.stopListening()` on `componentWillUnmount`.

```
class ViewModel extends ObservableObject {
  constructor(...args) {
    super(...args);
    this.listenTo("value", (e, newVal) => {
      this.onChange(newVal);
    });
  }

  get value() {
     return someObservable.property;
  }
}
```

For `connect()` and `componentFromViewModel()` though, we will need to call `.stopListening()` in RVM.
THoughts?

**Comment by justinbmeyer** [comment]
```
connectedCallback(el){
  // initialization and side-effects
  return () => {
    // teardown
    this.stopListening(); //-> called by default
  }
}
```

**Comment by christopherjbaker** [comment]
[Fixed](https://github.com/bitovi/ylem/commit/6ea30e415e6dceeced8fbf33d8eb4386b70ec174#diff-929d62aee2491b6d2f674e83b25b0a55R49)
