### ISSUE TITLE
rename exports and use named imports

### ISSUE THREAD

**Issue by christopherjbaker** [bitovi/ylem#134]
There are a few reasons to use named imports rather than everything attached to a default export (namely tree-shakability). In the case of react, extending `Component` (or `React.Component`, but we can't do this for obvious reasons) instead of `ylem.Component` enables the use of a number of eslint plugins that most react projects have enabled by default.

Doing this, however, creates naming collisions with `Object` and `Array`. Unlike in can observe, these are no longer meant as generic observables but are instead specifically for creating your ViewModel, so I would propose that we rename them to `ViewModel`/`Model` and `ModelList` respectively (mirroring how they might be used to create `Employee` and `EmployeeList`). Even besides the name collisions, naming semantics are important.

**Comment by justinbmeyer** [comment]
Naming them ViewModel would lock them into being used on ViewModels. If a Model or some other observable is needed, it would be odd. 

I’d suggest ObsObject or observe.Object

**Comment by justinbmeyer** [comment]
observe.Object is probably best because canjs’s Docs will make sense immediately

**Comment by christopherjbaker** [comment]
I had amended my original post to alias `Object` as both `ViewModel` and `Model`, and `Array` as `ModelList`. Within ylem, these are how they will be used, so I don't think anything will be lost by locking them down.

When using can-observe directly, I use `ObserveObject` to prevent the collision, so certainly not opposed to that (tbh, I think can-observe should do this). I really think we should take advantage of the opportunity to give it a semantically appropriate name though.

**Comment by justinbmeyer** [comment]
It seems that most types that are generic usually seem to get the generic name instead of the specific use case.  If we bring in other observable types like single-value, observations, streams, etc, I think they should be named based on their “computer sciency datatype” instead of initial use case.

**Comment by DesignByOnyx** [comment]
We have agreed upon `ObserveObject` and `ObserveArray` - that change will be coming out soon.
