### ISSUE TITLE
Create an assignDeep  which ignores React objects.

### ISSUE THREAD

**Issue by DesignByOnyx** [bitovi/ylem#141]
This is related to the code written in #140 - basically, we need a way to do deep assign but have special treatment for React objects.

**Comment by christopherjbaker** [comment]
it should also check objects and arrays to make sure they are extensible, and do a shallow clone if they are not, or updates break. (this is why the `deep-assign` branch clones children`

**Comment by christopherjbaker** [comment]
They are plain js objects, that don't extend anything, and they are frozen
during dev. Unless we can somehow sneak it in before they are frozen
(highly unlikely, but maybe by overwriting some internal method), I don't
think so.

**Comment by justinbmeyer** [comment]
```
ylem(VM, ReactComponent)
```

```
ylem = function(vm, Comp){
  Comp.React
}
```

```
reflect.serialize = function( obj ){
  if(React.isComponent( obj ) {
     return obj;
   } else {
    return oldSerialize.call(reflect, obj)
   }
}
```

**Comment by justinbmeyer** [comment]
```

ourAssign = function(v1, v2){
  if(React.isComponent( obj ) {
     return obj;
  } else {
    reflect.assignDeep(v1, v2, ourAssign);
  }
}
```
