### ISSUE TITLE
Github banner -> Potential Security Vulnerability

### ISSUE THREAD

**Issue by BigAB** [bitovi/ylem#166]
So, no one is going to use our library if we can't get this banner off the front page of our repo:

<img width="1056" alt="sec-vuln-pop-up" src="https://user-images.githubusercontent.com/76821/41682764-e0701208-7495-11e8-8cb3-0fe2fb4bd1a8.png">

So, we should find the package causing this, and remove or update it so this goes away.

**Comment by christopherjbaker** [comment]
Did you read teh last line of the banner? =P

On a serious note though, this is caused by an old version of `growl`, which is used by an old version of `mocha`, which used by `testee`. See the critical section of bitovi/testee#172

**Comment by justinbmeyer** [comment]
I wish they could see this is a dev dep.
